In [1]:
pip install numpy 

You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
#Task 1 - create a 1D array of numbers from 0 to 9
array = np.array([0,1,2,3,4,5,6,7,8,9])

print (array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#Task 2 - Create a 3×3 NumPy array of all Boolean value Trues

array_3D = np.ones((3,3))

print (array_3D)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
#Task 3 - Extract all odd numbers from array of 1 - 10

array = np.array([1,2,3,4,5,6,7,8,9,10])

result = []

for i in array:
    if (i % 2) != 0:
        result.append(i)

print (result)

[1, 3, 5, 7, 9]


In [6]:
#Task 4 - Replace all odd numbers in an array of 1-10 with the value -1

array = np.array([1,2,3,4,5,6,7,8,9,10])

array = np.where(array % 2 != 0, -1, array)

print (array)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [7]:
#Task 5 - Convert a 1D array to a 2D array with 2 rows

num = int(input("How many numbers would you like in your array?"))

array = np.arange(num)

col = len(array) / 2
col = int(col)

newArray = array.reshape(2, col) 
# rows then columns when creating the matrix

print(newArray)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
#Task 6 -   Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals

a = np.array([2,4,6,8,10,12,14,16,18])
b = np.array([1,3,5,7,9,11,13,15,17])

a = a.reshape(3,3)
b = b.reshape(3,3)

print ("Matrix stack : \n")
print(a)
print(b)

c = np.dot(a,b)
print ("\n Dot totals for stack : \n")
print(c)

d = np.sum(c, axis =1)
print ("\n Sum totals for rows: \n")
print(d)

e = np.sum(c, axis =0)
print ("\n Sum totals for colunns: \n")
print(e)

f = np.sum(c)
print ("\n Overall sum of stack: \n")
print (f)

Matrix stack : 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]

 Dot totals for stack : 

[[108 132 156]
 [234 294 354]
 [360 456 552]]

 Sum totals for rows: 

[ 396  882 1368]

 Sum totals for colunns: 

[ 702  882 1062]

 Overall sum of stack: 

2646
